w5d1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands
  resources :albums
  resources :tracks
end

w5d1/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :yr, presence: true
  validates_inclusion_of :is_live, in: [true, false]


  belongs_to :band

  has_many :tracks

  def band_name
    band.name
  end
end

w5d1/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
  has_many :tracks,
    through: :albums
end

w5d1/music_app/app/models/note.rb
class Note < ApplicationRecord
  validates :body, presence: true;

  belongs_to :user
  belongs_to :track
end

w5d1/music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :title, :ord, :album_id, presence: true
  validates_inclusion_of :is_regular, in: [true, false]

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes

    def band_name
      band.name
    end

    def album_title
      album.title
    end
end

w5d1/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, not_nill: false}

  after_initialize :ensure_session_token
  attr_reader :password


  has_many :notes

  def reset_session_token!
    token = rand_token
    self.session_token = token
    self.save
    token
  end

  def rand_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= rand_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    self.save
  end

  def valid_password?(password)
    digest = self.password_digest
    BCrypt::Password.new(digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.valid_password?(password)
      return user
    else
      return nil
    end
  end

end

w5d1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :verify_login


  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_album_url
    end
  end

  def new
    @album = Album.new
    render :new
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.delete
    redirect_to albums_url
  end

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])
  end

  private
    def album_params
      params.require(:album).permit(:title, :band_id, :yr, :is_live)
    end

end

w5d1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :authenticity_token, :current_user, :all_bands, :all_albums

  def authenticity_token
    html = "<input type='hidden' name='authenticity_token' value = '<%=authenticity_token%>'\> "
    html.html_safe
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
    return @current_user if @current_user
    return false
  end

  def log_in_user!(user)
    token = user.ensure_session_token
    session[:session_token] = token
  end

  def all_bands
    Band.all
  end

  def all_albums
    Album.all
  end

  def verify_login
    redirect_to new_session_url unless current_user
  end


end

w5d1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :verify_login


  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.delete
    redirect_to bands_url
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      redirect_to bands_url
    end
  end


  private
    def band_params
      params.require(:band).permit(:name)
    end

end

w5d1/music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

w5d1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ["invalid username/password"]
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
    else
      render :new
    end
  end


end

w5d1/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :verify_login

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_track_url
    end
  end

  def new
    @track = Track.new
    render :new
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.delete
    redirect_to tracks_url
  end

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find_by(id: params[:id])
  end

  private
    def track_params
      params.require(:track).permit(:title, :ord, :is_regular, :album_id, :lyrics)
    end

end

w5d1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def new
    render :new
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

w5d1/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

w5d1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w5d1/music_app/app/helpers/notes_helper.rb
module NotesHelper
end

w5d1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1/music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

w5d1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

w5d1/music_app/app/views/albums/_album_form.html.erb
<% if type == :create %>
  <% action = albums_url %>
<% else %>
  <% action = album_url(album) %>
<% end %>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>
<form class="form" action="<%=action%>" method="post">
  <%= authenticity_token %>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authenticity_token %>
  <label>Album Title:</label>
  <input type="text" name="album[title]" " value="<%= album.title %>">
  <label>Album Year:</label>
  <input type="number" name="album[yr]"  value="<%= album.yr %>">
  <label>Band:</label>
  <select type="text" name="album[band_id]" >
    <option <%= "selected" if type == :create %> disabled>-Select Band - </option>
    <% all_bands.each do |band| %>
      <option value="<%=band.id%>" <%= "selected" if @album.band == band.id %>>
        <%=band.name%></option>
      </option>
    <% end %>
  </select>
  <section class="radio-buttons">
    <label>Live:</label>
    <input type="radio" name="album[is_live]" value="true" <%= "checked" if @album.is_live  %> >
    <label>Studio:</label>
    <input type="radio" name="album[is_live]" value="false" <%= "checked" if !@album.is_live  %> >
  </section>
  <% submit_text = (type == :create) ? 'Create Album' : 'Edit Album' %>
  <input type="submit" value="<%=submit_text%>">
</form>

w5d1/music_app/app/views/albums/edit.html.erb
<section class="form-container">
  <div class="title">
    <h1> Edit Album </h1>
  </div>
  <%= render "album_form", album: @album, type: :edit %>
</section>

w5d1/music_app/app/views/albums/index.html.erb
<ul class="album-list">
  <% @albums.each do |album| %>
    <li><h2> <%= album.title %> by <i><%= album.band_name %></i></h2></li>
  <% end %>
</ul>

<%= button_to "Create New Album", new_album_url, method: :get %>

w5d1/music_app/app/views/albums/new.html.erb
<section class="form-container">
  <div class="title">
    <h1> Edit Album </h1>
  </div>
  <%= render "album_form", album: @album, type: :create %>
</section>

w5d1/music_app/app/views/albums/show.html.erb
<section class="info-page">
  <section class="data">
    <h1> <%= @album.title %> </h1>
    <strong>band:</strong> <%= @album.band_name %><br>
    <strong>yr:</strong> <%= @album.yr %><br>
    <strong>live:</strong> <%= @album.is_live %><br>

    <h2> Tracks </h2>
      <ul>
      <%@album.tracks.each do |track| %>
        <li> <%= link_to track.title, track_url(track) %> </li>
      <% end %>
  </section>
  <section class="buttons">
    <%= button_to "Edit Album", edit_album_url(@album), method: :get, class: "option-button" %>
    <%= button_to "Delete Album", album_url(@album), method: :delete, class: "option-button" %>
  </section>
</section>

w5d1/music_app/app/views/bands/_band_form.html.erb
<% if type == :create %>
  <% action = bands_url %>
<% else %>
  <% action = bands_url(band) %>
<% end %>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>
<form class="form" action="<%=action%>" method="post">
  <%= authenticity_token %>
  <% if type == :update %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authenticity_token %>
  <label>Band Name:</label>
  <input type="text" name="band[name]" placeholder="AC/DC" value="<%= band.name %>">
  <% submit_text = (type == :create) ? 'Create Band' : 'Edit Band' %>
  <input type="submit" value="<%=submit_text%>">
</form>

w5d1/music_app/app/views/bands/edit.html.erb
<section class="form-container">
  <div class="title">
    <h1> Edit Band </h1>
  </div>
  <%= render "band_form", band: @band, type: :edit %>
</section>

w5d1/music_app/app/views/bands/index.html.erb
<ul>
  <% @bands.each do |band| %>
    <li><h2> <%= band.name %> </h2></li>
  <% end %>
</ul>

<%= button_to "Create New Band", new_band_url, method: :get %>

w5d1/music_app/app/views/bands/new.html.erb
<section class="form-container">
  <div class="title">
    <h1> Create Band </h1>
  </div>
  <%= render "band_form", band: @band, type: :create %>
</section

w5d1/music_app/app/views/bands/show.html.erb
<section class="band_page">
  <h1> <%= @band.name %> </h1>
  <section class="data">
    <h2> Albums </h2>
      <ul>
      <%@band.albums.each do |album| %>
        <li> <%= link_to album.title, album_url(album) %> </li>
      <% end %>
  </section>
  <%= button_to "Edit", edit_band_url(@band), method: :get, class: "option-button" %>
  <%= button_to "Delete Band", band_url(@band), method: :delete, class: "option-button" %>
</section>

w5d1/music_app/app/views/layouts/_header.html.erb
<header>
  <img class="logo" src="https://cdn3.iconfinder.com/data/icons/ultimate-social/150/41_itunes-512.png"/>
  <section class="title"> dope music app </section>
  <section class="user-options">
    <% if current_user %>
    <span class="user-email"><%= current_user.email %></span>
      <%= button_to "Log Out", session_url, method: :delete  %>
    <% else %>
      <%= button_to "Sign Up", new_user_url, method: :get  %>
      <%= button_to "Sign In", new_session_url, method: :get  %>
    <% end %>
  </section>
</header>

w5d1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="content">
      <%= render "layouts/header" %>
      <section class="main-content">
        <%= yield %>
      </section
    </div>
  </body>
</html>

w5d1/music_app/app/views/users/new.html.erb
<section class="form-container">
  <div class="title">
    <h1> Sign Up </h1>
  </div>
  <%= render "shared/form", type: :register %>
</section>

w5d1/music_app/app/views/users/show.html.erb
<h1> Show page for: <%=@user.email %> </h1>